#========================================================================
# Copyright 2023 Universidade Federal do Espirito Santo
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
# 
# This program is released under license GNU GPL v3+ license.
#
#========================================================================

# Docs:
#   https://hub.docker.com/_/mysql
#   https://dev.mysql.com/doc/refman/8.0/en/replication.html
#
# Refs:
#   https://www.ctl.io/knowledge-base/servers/configuring-mysql-for-high-availability/
#   https://github.com/vbabak/docker-mysql-master-slave/
#   https://dev.mysql.com/doc/refman/8.0/en/change-master-to.html#:~:text=MASTER_LOG_POS%20is%20the%20numeric%20position,is%20for%20GTID%2Dbased%20replication.
#   https://stackoverflow.com/questions/56190169/how-can-i-use-an-environment-variable-in-the-mysql-console
#
# How to run it:
#   docker-compose up -d
#
# How to stop it:
#   docker-compose down
#
# Tear down:
#   docker volume prune

version: "3.9"

services:

  # source node
  master:
    image: mysql:8
    restart: unless-stopped
    env_file:
      - ./env/master.env
    environment:
      - MYSQL_ROOT_PASSWORD=Example@1
    volumes:
      - ./conf/master/mysql.conf.cnf:/etc/mysql/mysql.cnf
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - backend

  # replica node
  slave:
    image: mysql:8
    depends_on:
      - master
    restart: unless-stopped
      ## environment:
      ##  - MYSQL_ROOT_PASSWORD=Example@1
    env_file:
        - ./env/slave.env
    volumes:
      - ./conf/slave/mysql.conf.cnf:/etc/mysql/mysql.cnf
    networks:
      - backend

  adminer:
    image: adminer
    depends_on:
      - master
      - slave
    restart: unless-stopped
    networks:
      - backend
      - frontend
    ports:
      - 8080:8080

networks:

  backend: # hidden from the world
    internal: true

  frontend: # visible to the world
    driver: bridge
